### ISSUE TITLE
Dev Java

### ISSUE THREAD

**Issue by fernandajesus** [soujava/vagas-java#1001]
**RESPONSABILIDADES E ATRIBUIÇÕES
Esse profissional irá:**

Desenvolver soluções com foco em qualidade, disponibilidade, seguindo práticas Ágeis e melhores padrões de Arquitetura.
Planejar tasks nas práticas ágeis do SCRUM.
Elaborar documentação de projetos de software.
Atuar como Líder Técnico nos projetos sendo a referência técnica para o time de desenvolvimento.

**REQUISITOS E QUALIFICAÇÕES**
Pra mandar bem nessa oportunidade você precisa manjar das tecnologias:

Experiência em desenvolvimento em JAVA 8, JPA (Hibernate), Spring / Spring boot, Maven / Jenkins, WSDL, webservice, (SOAP e REST), Cluster / JBOSS, Camel e JMS.
Conhecimento em Banco de dados relacional e não relacional;
APIs RESTful;
Spring Framework, SpringBoot;
SQL e banco de dados PostgreSQL, Oracle ou SQL Server;
GIT, Docker, Jenkins, GitLab CI;
Testes Unitários e Integração;
Padrões de Projetos;

**Vai ser massa se você também tiver:**

Experiência na construção de serviços e microserviços;
Conhecimento em Bases NoSQL;
Conhecimentos em conceitos de design de software sob cultura DEVOPs;
Proficiência em desenvolvimento e entrega de software em ambiente Cloud (AWS ECS, Kubernetes).

**INFORMAÇÕES ADICIONAIS
O que não abrimos mão:**

Mindset focado em construir soluções criativas;
Capacidade de aprender com experiências de outros como também compartilhar suas próprias experiências;
Ser apaixonado por tecnologia;
Comprometimento em um ambiente voltado a entregas de alta colaboração.

**Para esta posição oferecemos:**

Salário CLT Full;
Vale Refeição ou Alimentação (Alelo);
Vale Transporte (sempre que houver o deslocamento);
Auxílio Home Office (proporcional aos dias em que atuará nesta modalidade);
Assistência Médica Sulamérica;
Assistência Odontológica Sulamérica;
Gympass;
Clube de benefícios Allya;
Seguro de Vida;
Parcerias (Curso de idiomas, ensino, livraria, restaurante);
Inside Out (Ocorre todas as sextas-feiras. Evento voltado para troca de conhecimento);
Oportunidade de crescimento profissional.

**Comment by KlausEverWalkingDev** [comment]
O que fazer para participar do processo seletivo?

**Comment by fernandajesus** [comment]
Olá, Klaus

Você pode se candidatar diretamente na Gupy: `https://solutis.gupy.io/jobs/890111` ou pode enviar seu curriculo para mim no e-mail: fernanda.silva@solutis.com.br
