### ISSUE TITLE
[ATUAÇÃO REMOTA] Desenvolvedor Backend Java | DQR TECH

### ISSUE THREAD

**Issue by DaianeMFirmiano** [soujava/vagas-java#1180]
SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

CONTRATAÇÃO: PJ - 40h (semanais) em até 16k
Oportunidade com 21 dias de descanso + Notebook para o desempenho das atividades!

DESAFIO: 
Atuar em uma Fintech de soluções tecnológicas para operações financeiras, presente em 9 países de 4 continentes e disponibilizando diversos serviços em grandes players do segmento financeiro. 

REQUISITOS:
Desenvolvimento em Java / Node JS;
Conhecimento básico em Linux;
Execução de testes de unidade, funcionais e de integração;
Versionamento com Git;
Arquitetura de microsserviços;
Domínio de orientação a objetos;
Spring Boot e utilização de APIs RESTFull;
Banco de dados relacional Postgres SQL;

DESEJÁVEL:
Experiência em Meios de Pagamento;
Conhecimento de metodologias ágeis de desenvolvimento como Scrum, Kanban;    
Experiência com cartões de crédito/débito e sistemas de liquidação;
ISO 8583;  
Conhecimento dos conceitos de Cloud Computing e Amazon Web Services como: ECS, EC2, ECR, ELB, S3;    
Conhecimento dos conceitos de aplicações em cluster, Docker;
Conhecimento de sistemas de mensageria (Ex: ActiveMQ, RabbitMQ, Kafka, IBM MQ);

Envie seu currículo para: vagas@dqrtech.com.br ou chame no Whatsapp (51) 97633298 (Gabriela de Abreu)
Link direto Whatsapp: https://lnkd.in/eNwNcVxq

**Comment by gsabreudev** [comment]
Pode nos chamar pessoal!!
Meu whats: https://lnkd.in/eNwNcVxq
