### ISSUE TITLE
[Remoto] Vaga para Dev Java e Tech Lead!! (Todas as Senioridades)

### ISSUE THREAD

**Issue by ErikNoriki** [soujava/vagas-java#1386]
Olá pessoal! 

Estamos com vagas abertas para desenvolvedores JAVA Júnior, Pleno e Sênior, Além de Tech Lead Java no ANYMARKET! Todas as vagas são CLT e Remotas (Home-Office)

O ANYMARKET é uma plataforma de marketplaces, criada e desenvolvida pelo Grupo DB1, com foco no universo do ecommerce. Uma solução para conectar empresas a mais de 30 marketplaces como B2W (Americanas Marketplace), Magazine Luiza, Via Varejo, Amazon, Mercado Livre, Shopee, Carrefour, Netshoes, entre outros. Além disso, o grupo DB1 é 12 anos consecutivos uma empresa GPTW! Aqui a nossa cultura é YOU MATTER, além de proporcionar vários benefícios aos colaboradores, com o Personal Experience.

CASO TENHA ALGUM INTERESSE NAS VAGAS, ENTRE EM CONTATO COMIGO ATRAVÉS DO MEU LINKEDIN: https://www.linkedin.com/in/erik-noriki/

### Requisitos para a Vaga de Desenvolvedor JAVA Júnior

**Essa vaga exige que você tenha algum conhecimento em:**

- Java 8 +;
- Conhecimento em Spring e Spring Boot;
- Conhecimento em arquitetura de microsserviços;
- Atuação com banco de dados relacionais e não relacionais;
- Cultura forte de testes unitários e integração;
- Experiência com versionamento de código (GIT);
- Design Patterns e Clean Code. 

 
**Pode ser um diferencial:**

- Tiver fluência em inglês e espanhol;
- Conhecimento em uso de aplicações com Containers (Docker), Kubernets;
- Conhecimento em Ambiente de nuvem (AWS);
- Conhecimento em integrações com API SOAP / Rest;
- Atuação com servidores de aplicação (TomCat, JBoss).

**O ANY faz parte do DB1 Group e aqui você irá encontrar:**

- Qualidade em todos os aspectos.
- Muita oportunidade de Crescimento.
- Liberdade e autonomia, para sugerir, criar e mudar.
- Atuação em soluções globais.

### Requisitos para a Vaga de Desenvolvedor JAVA Pleno/Sênior

**É imprescindível que você conheça:**
- Java 8 +.
- Conhecimento em Spring e Spring Boot.
- Conhecimento em arquitetura de microsserviços.
- Atuação com banco de dados relacionais e não relacionais.
- Cultura forte de testes unitários e integração.
- Experiência com versionamento de código (GIT).
- Design Patterns e Clean Code. 

**Pode ser um diferencial:**
- Tiver fluência em inglês e espanhol.
- Conhecimento em uso de aplicações com Containers (Docker), Kubernets.
- Conhecimento em Ambiente de nuvem (AWS).
- Conhecimento em integrações com API SOAP / Rest.
- Atuação com servidores de aplicação (TomCat, JBoss).

**O ANY faz parte da DB1 Group e aqui você irá encontrar:**
- Qualidade em todos os aspectos.
- Muita oportunidade de Crescimento.
- Liberdade e autonomia, para sugerir, criar e mudar.
- Atuação em soluções globais.

### Requisitos para a Vaga de Tech Lead JAVA

**É imprescindível que você conheça:**
- Java (8+);
- Spring Framework;
- Conhecimento em Mensageria, Redis;
- Conhecimento em Microsserviços;
- Conhecimento em Testes automatizados;
- Conhecimento em boas práticas (GRASP, SOLID)
- Conhecimento em Arquitetura de Software (Clean Architecture; Hexagonal Architecture)

**Pode ser um diferencial:**
- Experiência prévia como Tech Lead;
- Espanhol intermediário
- Conhecimento em uso de aplicações com Containers (Docker), Kubernets;
- Atuação com servidores de aplicação (TomCat, JBoss).
- Conhecimento em AWS e VSTS;

**O ANY faz parte da DB1 Group e aqui você irá encontrar:**
- Qualidade em todos os aspectos.
- Muita oportunidade de Crescimento.
- Liberdade e autonomia, para sugerir, criar e mudar.
- Atuação em soluções globais.

**Comment by Guedesou** [comment]
Erik, bom dia! 🌞👩‍🚀
---
Eu vou colocar o meu aqui, mas vou te mandar uma mensagem por lá também!  Muito obrigado pela oportunidade. 
[Thiago Guedes- Dev.pdf](https://github.com/soujava/vagas-java/files/8778959/Thiago.Guedes-.Dev.pdf)
