### ISSUE TITLE
[Remota] Desenvolvedor Java Spring - JUNIOR na Ajax - Advanced Technological Solutions  

### ISSUE THREAD

**Issue by Nivea642130** [soujava/vagas-java#1387]
## Nossa empresa
Produzir resultados é o que nos move, é o que nos impulsiona. A Ajax é especialista em soluções tecnológicas de alta performance, que vão transformar sua empresa, aumentando a produtividade e conferindo maior eficácia e segurança a seus processos e atividades.

## Descrição da vaga

Desenvolvedor Java Spring

## Local
 Remoto

## Requisitos

**Formação:**
- Nível superior em andamento em Computação, Informática, Análise de Sistemas ou correlatos.

**Obrigatórios**
- Conhecimentos sólidos em Java Spring e demais frameworks padrões do stack;
- Conhecimentos sólidos em Angular e Vue.js

## Benefícios
🍎 VR ou VA (você escolhe!);
🤑Dinheiro no bolso no último dia útil do mês;
🏥 Plano de saúde e odontológico Bradesco Nacional 100% (sem coparticipação);
🍼 Auxílio creche para filhos com até 3 anos de idade (mães);
🥉incentivo à certificação dos nossos colaboradores;
🚴‍♀️ nosso programa de qualidade de vida e bem-estar: TotalPass (convênio de   academias  com mais de 250 modalidades distribuídas em mais de 2000 academias);
🍉VR Nutrição (chat com nutricionistas, acompanhamento das suas refeições e sugestões para implementar em seus hábitos alimentares);
🧡 Sexta-feira casual DAY.

## Contratação

📝 CLT Full;

## Como se candidatar

Por favor envie um e mail para vagas@ajaxti.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Java Spring

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: nivea.chaves@ajaxti.com.br
WhatsApp 85 98807 8300

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Junior

**Comment by Guedesou** [comment]
Nivea, bom dia! 🌞👩‍🚀
---
Será que tem como eu enviar meu CV por outro caminho? è que estou temporariamente sem e-mail. Roubaram meu celular no ônibus e o google bloqueou minha conta. Eu vou colocar o meu aqui, mas se puder te enviar por outro caminho. Muito obrigado por tudo. 
[Thiago Guedes- Dev.pdf](https://github.com/soujava/vagas-java/files/8778959/Thiago.Guedes-.Dev.pdf)
