### ISSUE TITLE
Desenvolvedor Java - 100% home office.

### ISSUE THREAD

**Issue by StefaniaClemente** [soujava/vagas-java#1433]
**O que você irá realizar:**
Executar o desenvolvimento de sistemas informatizados adequando-os às necessidades das áreas e clientes visando racionalizar ou automatizar processos e rotinas de trabalho.
Acompanhar, junto ao analista de sistemas, a implantação do novo projeto e sugerir melhorias no processo;
Participação em projetos de desenvolvimento de produtos para instituições financeiras ou fintechs.

**O que você precisa ter:**
Superior completo em Ciências da Computação, Analise e Desenvolvimento de Sistemas, Engenharias e áreas correlatas;
Inglês nível intermediário;
Dominio atuando com Java;
Experiência com Banco de Dados (DML, DDL, Oracle, SQL, DB2);
Experiência com Controlador de Versão e Teste de Perfomance (JUnit);
Sólidos conhecimentos com Sistema Operacional (Linux, UNIX), Websphere Application Server,   JBoss, Websphere MQ;
Vivências com XML, XSD, Json;
Entendimento de HTML, JavaScript, CSS, Wicket;
Conhecimentos com Webservice, Segurança e Negociações.

**Comment by AlexandreJusten** [comment]
como posso me candidatar?
