### ISSUE TITLE
[Brasília, DF] Desenvolvedor Java | B2HR

### ISSUE THREAD

**Issue by carolineevelin** [soujava/vagas-java#1598]
Olá! Somos da B2HR, uma empresa de Consultoria de RH de Brasília. Estamos apoiando um dos nossos clientes na busca de um Desenvolvedor Java Full Stack. A empresa que o novo contratado trabalhará, atua prestando serviço e desenvolvendo sistemas para a área de trânsito, então, terá contato com tecnologias de reconhecimento facial e de geolocalização. 

### ATIVIDADES
- Desenvolvimento em Java de aplicações para o segmento de trânsito, transporte, logística, seguros, depósitos, vistoriadoras, clínicas, autoescolas, gestão de frotas de veículos;
- Desenvolver sistemas para plataformas Web e Mobile, com páginas responsivas;
- Conduzir desenvolvimento de projetos de inovação end-to-end (Full Stack);
- Analisar e pesquisar inovações do mercado para desenvolvimento de novos produtos e agregar valor ao portfólio de produtos da empresa;
- Implementação de processos digitais, incluindo workflow, gestão de documentos, reconhecimento facial e certificados digitais; e
- Trabalhar orientado por Metodologias Ágeis.

### REQUISITOS
- Graduação completa: Cursos da área de TI;
- Experiência prévia com Desenvolvimento Ágil;
- Programação Java nas plataformas WEB e Mobile (iOs e/ou Android) com páginas responsivas;
- Plotagem de trajetos em mapas digitais (Google Maps ou similar);
- Programação IoT utilizando Raspberry e/ou Arduino;
- Biblioteca OPENCV;
- Comunicação GPIO e/ou CAN, GPS, câmeras de vídeo, modem, dentre outros componentes.

**Desejável** 
Desejável certificação Java, SCRUM ou DEVOPS; 
 Desejável experiência no desenvolvimento de aplicações com reconhecimento facial e/ou integração com a plataforma de identidade digital e-Gov.

### BENEFÍCIOS
Vale Transporte; 
Vale Alimentação;
Plano de Saúde Sulamérica;
Gympass.

**Estamos colhendo as pretensões salariais**

### LOCAL
Presencial: Asa Norte, Brasília - DF

### COMO SE CANDIDATAR
Link da vaga na Empregare: https://b2hr.empregare.com/v42018
Ou envie seu cv para: caroline.evelin@b2hr.com / (61) 98174-0348

**Comment by dalaohuniu** [comment]
good idea
