### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Backend Java | Improving

### ISSUE THREAD

**Issue by rodimes** [soujava/vagas-java#17]
Que tal trabalhar numa empresa premiada pelo Oscar da comunidade Java, que continua crescendo na crise, como desenvolvedor backend, podendo focar na área que mais gosta, construindo uma aplicação com dezenas de milhões de acessos, usando microsserviços, Big Data e várias tecnologias modernas?

Você será contratado em regime CLT full para trabalhar na região do Jaguaré em São Paulo, a 20 minutos a pé da estação Villa-Lobos da CPTM e com estacionamento gratuito para funcionários. A empresa iniciou suas atividades há 8 anos como startup e hoje já conta com cerca de 200 funcionários, sendo 30 diretamente técnicos, não incluindo neste número a área de negócios, produto e outras correlatas. O crescimento continua forte pela atuação no segmento de comércio eletrônico de produtos de beleza, que não arrefece com a crise.

Quer você esteja iniciando na carreira ou já seja experiente, você poderá:

- Criar um backend moderno, baseado em Java SE 8, microsserviços e APIs RESTful, utilizando as melhores práticas e explorando novas formas de atender dezenas de milhões de requisições por dia;
- Trabalhar com tecnologias como Spring Boot, Groovy, Postgres, MongoDB, Redis, Redshift, RabbitMQ, Spark e ElasticSearch, entre outras;
- Aprender muito todos os dias e superar novos desafios!

**Por que eu deveria me candidatar a essa vaga:**

- Ter a oportunidade de trabalhar numa empresa que respira tecnologia, não tem medo de experimentar e que deseja que você possa ser feliz atuando na área que mais te interessa, como otimização de busca, sistemas de recomendação, Big Data etc;
- Ajudar a moldar os squads que estão se formando e evoluindo para atender às crescentes demandas de negócio numa empresa reconhecida pela Oracle como uma das mais inovadoras no comércio eletrônico da América Latina, com quase uma centena de JVMs sustentando a operação;
- Você será contratado em regime CLT, com salário competitivo, convênio médico Amil, seguro de vida, vale refeição e vale transporte ou combustível;

**Para se candidatar, você precisa ter:**

- Espírito de trabalho em equipe, comprometimento e vontade de por a mão na massa;
- Capacidade de aprender rapidamente tecnologias emergentes mediante ao consumo de livros, documentação técnica, vídeos ou palestras em inglês;
- Domínio de orientação a objetos, Java SE 8 (incluindo lambda) e suas APIs principais (java.lang, Collections, streams, etc);

**Alguns diferenciais serão:**

- Domínio de arquiteturas RESTful e APIs com a plataforma Spring;
- Profundo conhecimento aplicado de mensageria;
- Conhecimento prático de técnicas para escalar serviços a fim de atender centenas de milhões de requisições por dia;
- Experiência com diversos sabores de persistência de dados e caching;
- Conhecimentos de segurança;
- Conhecimentos de cloud, entrega contínua e automação de infraestrutura em geral;

**Como se candidatar:**

Basta entrar no seguinte link: https://goo.gl/a1gewb , preencher nome e email e te enviaremos as instruções.

**Comment by CesarNog** [comment]
Obrigado por adicionar esta vaga aqui @rodimes 

Sinta-se livre sempre que quiser publicar vagas Java aqui!
