### ISSUE TITLE
[São Paulo] Desenvolvedor(a) JAVA SR. - DQR Tech 

### ISSUE THREAD

**Issue by CarolCerqueira** [soujava/vagas-java#1725]
**Sobre a DQR TECH | Qualidade do começo ao fim**

A DQR TECH é uma consultoria parceira dos seus clientes, que possui um ecossistema de serviços, atuando de forma abrangente em todo ciclo de desenvolvimento de software.
Desde a concepção e desenvolvimento até a manutenção e sustentação.
Levando soluções aos seus desafios de tecnologia, na forma de Projetos, Outsoucing e Squad.

**O QUE NOS MOVE:**

Tecnologia & Pessoas! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente do setor financeiro.

**DE ONDE VOCÊ VAI TRABALHAR?**

Híbrido na Faria Lima em SP/SP (2x a 3x por semana).

**O SEU DESAFIO SERÁ:**

- Atuar junto à equipe de Desenvolvimento;
- Trabalhar com arquitetura orientada a microsserviços e modelo DevOps;
- Expandir o pipeline de produtos;
- Atuar nos projetos que consistem em aumentar e flexibilizar o negócio;
- Monitoramento, performance e manutenção de sistemas em Java e Kotlin.

**REQUISITOS:**

- Java 8+
- Kotlin
- Arquitetura de Microserviços
- Conceitos de Spring – Boot, Data, Security
- Domínio dos conceitos – SOLID, Design Patterns
- Rest – API

**DESEJÁVEL:**

- Conceitos de Mensageria – Kafka ou RabbitMQ
- Ferramentas AWS – S3, Secrets Manager, CloudWatch e CloudFormation
- Arquitetura Limpa – Clean Architecture
- Ferramentas de Devops – Git, Jenkins, Kubernetes, Datadog, Kibana

**O QUE SERIA LEGAL SE VOCÊ SOUBESSE:**

- Ter atuado no setor financeiro;
- Experiência em modelagem de dados em DDD.

**QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:**

Liderança, habilidades de comunicação, boa didática, iniciativa.

**O QUE OFERECEMOS PARA VOCÊ?**

- Auxílio alimentação no cartão Caju;
- Assistência médica e odontológica da Porto Seguro e Mediservice, gratuita para você (sem coparticipação ou mensalidade);
- Você ainda pode incluir seus dependentes legais com apenas 50% de desconto da mensalidade em folha;
- Oferecemos auxílio Psicológico através da PsicologiaViva, estendida para dependentes;
- Auxílio creche (segundo as condições vigentes da convenção coletiva do Sindpd-SP);
- Seguro de vida da Porto Seguro, em grupo;
- Auxílio Educação da Alura;
- Aqui a sua indicação vale premiação de 1K;
- No mês do seu aniversário tem presente;
- A cada aniversário de DQR Tech, você recebe um mimo;
- Notebook para o desempenho das atividades + kit de onboarding da DQR Tech;
- Contrato CLT.

Caso tenha interesse ou indicações entre em contato: **vagas@dqrtech.com.br**

![image](https://github.com/soujava/vagas-java/assets/154989598/956c9e2b-ea86-449f-a0b1-e0b66b7087ee)

**Comment by AndrewsCunha** [comment]
#vempraDQRtech

**Comment by AndrewsCunha** [comment]
Vem pra DQR Tech!

**Comment by robson2015xx** [comment]
Opa, enviei o currículo e topo qualquer desafio técnico :)
