### ISSUE TITLE
[Remote] Vaga de Java Full Stack SR na Encora BR!

### ISSUE THREAD

**Issue by recrutamentoencorabr** [soujava/vagas-java#1736]
## Descrição da vaga
 

Atividades:
Desenvolvimento de novas funcionalidades;
Manutenção de aplicações existentes;
Levantar e discutir trade-offs de diferentes abordagens de projeto elaborando documentos de projeto detalhados;
Implementar solução desde a codificação até o teste e suporte à implantação da produção;
Execute revisões de código.

Competências Essenciais:
Proficiência em Backend Java e Java Spring Boot;
Experiência com testes automatizados em Java (ex: Unit Test, Integration Test, etc.);
Experiência em desenvolvimento front-end, especialmente com React e forte compreensão dos princípios de UI/UX;
Experiência com Typescript;
Experiência com GraphQL;
Experiência com Arquitetura de Microsserviços;
Experiência com modelagem, produção e consumo de APIs baseadas em web services (baseadas em RESTful ou SOAP);
Bons conhecimentos em bancos de dados relacionais e não relacionais, ser capaz de trabalhar com Postgres e MongoDB;
Experiência no uso de serviços da AWS, particularmente ECS, Beanstalk, EC2, S3.
Familiaridade com RabbitMQ e Amazon SQS;
Compreensão prática de práticas de Git ou VCS, CI/CD semelhantes, com preferência por experiência em Ações GitHub ou Jenkins;
Utilização de ferramentas de monitoramento como Sumo Logic, New Relic, Datadog, ou soluções equivalentes para solução de problemas e registro;
Experiência com desenvolvimento ágil.

## Local

Remoto - full time - home office

## Contratação

- CLT + 100% remoto + benefícios.

## Nossa empresa

A Encora é uma fornecedora líder de soluções de software e engenharia digital, com 48 escritórios globais e uma equipe de mais de 9.000 Encorians. Estamos presentes em regiões ricas em tecnologia, equipados para oferecer serviços excepcionais em engenharia de produto, nuvem, modernização de dados, experiência digital e muito mais.

Nossa filosofia de contratação está enraizada na habilidade e no talento, promovendo um local de trabalho onde a diversidade e a inclusão se traduzam em soluções inovadoras para cada cliente.

## Como se candidatar

Para se candidatar basta acessar o link: https://careers.encora.com/application?&gh_jid=4203936007

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by PHAredes** [comment]
Mandei um email para vocês
