### ISSUE TITLE
[Araraquara, SP, Remoto e presencial] Java

### ISSUE THREAD

**Issue by netstart** [soujava/vagas-java#181]
Vaga: Senior Software Developer
Empresa: Invillia - https://www.invillia.com/ ou https://jobs.kenoby.com/invillia
Local: Araraquara - SP
Tipo: Presencial ou Remoto

![image](https://user-images.githubusercontent.com/200232/51110295-51db8e80-17df-11e9-867d-a8d6357ba255.png)

**Comment by netstart** [comment]
Informar indicação do Clayton Passos

**Comment by devthiagoh** [comment]
Essa vaga ainda está aberta? Não consegui acessar pelos links.

**Comment by I-am-Miguel** [comment]
@devthiagoh tenta esse link `https://jobs.kenoby.com/invillia`
