### ISSUE TITLE
Vagas Altran Portugal, Analista programador Java EE 

### ISSUE THREAD

**Issue by andersondebrito** [soujava/vagas-java#185]
Analista programador Java EE (4 anos de experiência)
 
Competências técnicas:
JSF 2.x / EJB 3.x / CDI 1.x / JPA 2.x / Hibernate / JMS / PrimeFaces
Java Swing / JDBC
HTML / CSS / Javascript / JQuery
Eclipse / Maven / Jenkins / SVN / Nexus
Glassfish / WebLogic 
Análise UML / Agile
SQL 
JUnit / TDD / Cucumber / Selenium
Integração Continua 
Fluência em Inglês (plus) 
Softskills: Dinamismo, pro-atividade,  facilidade de comunicação, comprometimento

Tem interesse? Me envia o cv atualizado anderson.oliveira@altran.com

**Comment by devthiagoh** [comment]
Home Office?
