### ISSUE TITLE
[ Campinas - SP ] [ Maringá - PR] [ São Paulo - SP] Analista de Sistemas - Java 

### ISSUE THREAD

**Issue by miron15** [soujava/vagas-java#187]
Formação Acadêmica 
Superior completo em Análise de Sistemas, Engenharia da Computação, Ciência da Computação, Sistemas de Informação ou cursos afins.

Competência Desejada 
Certificação Java Programmer será um diferencial;
Experiência com Scrum e Test Driven Development;
Conhecimento em RESTful, JavaScript e AngularJS;
Familiaridade com Git, Maven e Jenkins.

Competência Requerida 
Experiência em desenvolvimento Java / Web com Spring e Hibernate;
Flexibilidade para se adaptar a outras tecnologias Java.
Responsabilidades 
Atuar na análise, desenvolvimento, evolução e suporte de produtos de uso internos.

Para se candidatar enviar o CV: aline.miron@matera.com

**Comment by devthiagoh** [comment]
Home Office?
