### ISSUE TITLE
[São Paulo- SP] Desenvolvedor Back End Java Pleno- BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [soujava/vagas-java#192]
Empresa
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Descrição
Estamos em busca de profissionais que tenha experiência com programação em Java e Banco Oracle, para grande banco de investimentos. Contratação CLT, salário a combinar mais atrativo pacote de benefícios. Horário comercial.

Local
Faria Lima, perto da JK- SP. Estação de trem mais próxima- Cidade Jardim.

Como aplicar
Envie um e-mail para [ryokota@brq.com](mailto:ryokota@brq.com)

**Comment by AndersonMarquess** [comment]
Enviado.
