### ISSUE TITLE
Vaga: Desenvolvedor(a)  Java - São Paulo \ Maringá e Campinas

### ISSUE THREAD

**Issue by miron15** [soujava/vagas-java#199]
Tipo: CLT
Experiência: Júnior \ Pleno e Sênior
Vagas: 4

O que a Matera faz?
Com espírito de startup e mais de 30 anos de história, reconhecimento global e o compromisso de inovar sempre. Tudo para continuar desenvolvendo soluções e construindo parcerias que promovam a transformação digital e sem fronteiras, no mercado financeiro e de pagamentos , na gestão de riscos e no setor varejista . Essa é a Matera.

O QUE ESPERAMOS DE VOCÊ?
Você atuará na análise, desenvolvimento e suporte de sistemas, utilizando a linguagem Java. Também será responsável por visitar clientes dando apoio à análise e implantanção dos sistemas Matera.

Para isso buscamos alguém com:

Superior completo em Administração com ênfase em Tecnologia da Informação, Engenharia da Computação, Ciência da Computação, Análise de Sistemas ou afins.

Experiência em desenvolvimento Java / Web com Spring e JPA;
Experiência com desenvolvimento de RESTful API;
Experiência com desenvolvimento de testes automáticos;
Familiaridade com Git, Maven e Jenkins;
Flexibilidade para se adaptar a outras tecnologias Java.

Seria bacana se você tivesse - Isso é um plus ;)

Conhecimento em JavaScript, Angular e React;
Experiência com metodologias ágeis;
Certificação Java Programmer será um diferencial.

## Como se candidatar
Poderá enviar o CV para: aline.miron@matera.com

**Comment by savitoh** [comment]
Qual localidade?

**Comment by devthiagoh** [comment]
Home Office?
