### ISSUE TITLE
JAVA para Curitiba e Maringá ou remoto

### ISSUE THREAD

**Issue by netstart** [soujava/vagas-java#200]
Estamos com algumas oportunidades JAVA para Curitiba e Maringá ou remoto.

Caso tenha interesse e requisitos obrigatórios mencionados, por favor encaminhe seu currículo (contendo as exigências descritas) e pretensão salarial.

Caso não tenha interesse, fique a vontade para encaminhar para seus contatos.

Obrigada!

Vaga 1 - Desenvolvedor Java júnior, pleno e Sênior

CLIENTE: Empresa atuante no segmento de frotas.

LOCAL: Curitiba / PR - centro

MODELO DE CONTRATAÇÃO: PJ

TEMPO: INDETERMINADO

REQUISITOS

- Experiência com programação Full Stack (JAVA, Spring Framework, Spring Boot, Hibernate, Angular, Bootstrap, Ajax, JavaScript, HTML5);

- Experiência em bancos de dados relacionais e não relacionais;

- Experiência em metodologia ágil;

- Experiência em especificação e elaboração de arquitetura;

- Experiência em especificação de APIs REST;

- Experiência em Integração Contínua e DevOps;

- Experiência em Teste de software

Desejável  

- Conhecimento em Cloud Computing (AWS)

- Bancos NoSQL (MongoDB)

- Conhecimento em Ionic / Cordova (mobile development framework)

Vaga 2 - Desenvolvedor Java júnior

CLIENTE: Empresa atuante no segmento educacional

LOCAL: Curitiba / PR – Agua verde

MODELO DE CONTRATAÇÃO: PJ

TEMPO: INDETERMINADO

REQUISITOS

- Experiência com Java Web;

- Dominar a Orienteção a Objetos; 
- Dominar o conceito Restful e o protocolo Http;

Desejável

- TDD 
- AWS Aurora 
- AWS DynamoDB 
- AWS SQS, SNS 
- SQL

Vaga 3 - Desenvolvedor Java (BPM) Pleno e Sênior

CLIENTE: Empresa atuante no segmento de Tecnologia

LOCAL: Remoto ou em Maringá (Caso seja remoto, primeiro mês deverá ser em Maringá para integração.)

MODELO DE CONTRATAÇÃO: CLT

TEMPO: INDETERMINADO

REQUISITOS

- Conhecimento em Java;

- Conhecimento em BPM (mandatório) 
- Vivência em front-end e integração com back-end 
- Vivência com ambientes modernos de desenvolvimento integrado (IDE) como Eclipse ou RAD;

- Metodologias ágeis; 
- Vivência na implementação de projetos Java; 
- Conhecimento em HTML5, Javascript, Angular; 
- Ferramenta de colaboração Jira; 
- Automatização de testes.

Desejável  
- Experiência no ramo se seguros será um diferencial. 
- Experiência com Gosu será um diferencial.

Best Regards / Atenciosamente / Saludos,

Jaqueline Tatiane Oliveira
Associate Technical Recruiter

+55 41 2106 6953  | Office
jaque-tati | Skype

**Comment by devthiagoh** [comment]
Como aplico a vaga?
