### ISSUE TITLE
[Curitiba, PR] Desenvolvedor Java Pleno | BR CAPTURA

### ISSUE THREAD

**Issue by andreheidi** [soujava/vagas-java#24]
A BR CAPTURA, e uma empresa especializada em prover infraestrutura, gestão e monitoramento para redes de telecomunicações através das diversas tecnologias de conectividade.
Com capital e tecnologia nacionais, a BR CAPTURA nasce para ser vista como referência de qualidade e sustentabilidade para o “ecossistema corporativo” e objetiva gerar alto valor agregado, primando sempre pela excelência nos serviços e satisfação dos envolvidos na sua cadeia de negócios (clientes, fornecedores, colabores, acionistas e sociedade).
Nossa especialidade é fornecer conectividade para o mercado M2M e Internet of the Things (IoT) e suas diversas vertentes (cartões e meios de pagamentos, utilities (energia, agua, gás e saneamento), saúde, segurança, transporte e logística). Nossa plataforma (infraestrutura/software) foi projetada tendo em vista os desafios apresentados por este mercado em constante evolução: segurança, robustez, escalabilidade e flexibilidade.

Estamos com oportunidade, segue abaixo maiores informações da vaga:
Vaga: Analista Desenvolvedor Java
Requisitos:
Graduação completa em cursos relacionados à área.
Experiência de 2 ou mais anos com a linguagem Java (Servlets/JSF(Primefaces)/JPA/CDI/Bean Validator / Spring-boot).
Boa base de conhecimento em algoritmos e estrutura de dados.
RESTful API's.
Javascript/JQuery/Html/CSS.
SQL.
Linux/Unix.
Conhecimento em arquitetura em camadas.
Conhecimento em HTML, CSS e Javascript (nativos).
Uso de boas práticas de desenvolvimento em geral.

Requisitos Desejáveis:
Git / Maven / Eclipse.
Tomcat.
Redis / Mysql.
Sistemas de alta performance.
Sistemas analíticos de dados (Logstash, Elastic Search, Kibana, etc.).
SOA (Service-Oriented Architecture).
Experiência em metodologia SCRUM.
Contrato CLT

O profissional será responsável por:
Analisar requisitos.
Elaborar interfaces contratos, serviços e aplicar regras de negócios.
Desenvolver e refatorar código utilizando-se das melhores práticas.
Documentar para as demais equipes envolvidas no ciclo de desenvolvimento.
Participar das definições de arquitetura e tecnologia.
Trabalhar na evolução das diferentes camadas do sistema (Full-stack).
Documentar soluções/decisões técnicas quando necessário.
Reportar andamento das atividades entre diferentes times.
Analisar potenciais problemas de performance/capacidade e sugerir soluções.

Interessados encaminhar curriculo para luciana.lopes@inlog.com.br

**Comment by CesarNog** [comment]
Obrigado por publicar esta vaga aqui @andreheidi !

**Comment by andreheidi** [comment]
De nada @CesarNog
