### ISSUE TITLE
[Curitiba, PR] Desenvolvedor Java Junior/Pleno | UnitedHealth Group

### ISSUE THREAD

**Issue by andreheidi** [soujava/vagas-java#27]
Link da vaga: http://uhg.hr/DesenvolvedorJavaCuritibali

Qualificações Necessárias:
· Java, HTML 5, CSS, REST, SOAP, Scala, Oracle
· Desenvolvimento de código orientado a negócios (Domain driven design).
· Usando conceitos de programação funcional e orientada a objetos.
· Definir a integração da API entre sistemas que utilizam serviços da Web (SOAP e Rest)
· Pesquisa e solução de potenciais problemas na implementação do ambiente produtivo
· Propor soluções técnicas sobre as histórias apresentadas pelo Product Owner de sua equipe.

**Comment by CesarNog** [comment]
Obrigado por compartilhar esta vaga aqui, @andreheidi !
