### ISSUE TITLE
VAGAS JAVA SENIOR E PLENO

### ISSUE THREAD

**Issue by MarcosINOVATION** [soujava/vagas-java#293]
Oportunidade Desenvolvedor Java Pleno e Sênior para atuar em regime CLT Full em uma grande Empresa Multinacional Americana com presença Global lider de Mercado em Projeto do setor Automobilistico em SBC.

Excelente pacote de Benefícios:

- AM – Sulamerica, sem descontos para dependentes
- P. Odonto., tb sem desconto
- VR 600,00 por mes – ou no VA ou 50% em cada um
- VT opcional e desconto de 6%
- Seguro de vida
- Auxilio creche para crianças ate 5 anos
- PPR: 10% do salario anual = 1,2 de salario
- Academia : Gympass

Requisitos:

- Experiência comprovada em desenvolvimento em linguagens Java/ Java Web com SQL Server ou Oracle – se possível com Spring framework, Maven e/ou Websphere, micro serviços e/ou webservices, REST-HTTP;
- Desejável experiência com métodos ágeis.
- Habilidades e lógica de gerenciamento de arquivos/dados/shellscript.
- Conhecimento em sistemas de controle de versão de arquivos (git, github, gitlab).

Diferencial:

- Devops (Jenkins, Splunk, Puppet).
- Conhecimento ambiente Hadoop (HDFS, MapReduce).
- Domínio YARN, Resource Manager.

Posso contar contigo para este processo seletivo ?

Enviar CV para marcos.moura@inovation.com.br ou pode me chamar direto no Whats: 11 94024 0881

Grande Abraço

**Comment by danilosales** [comment]
Olá Marcos, esta vaga aceita trabalho remoto ou somente presencial ?

**Comment by MarcosINOVATION** [comment]
Somente presencial mesmo .. é para ficar alocado na FORD
