### ISSUE TITLE
[São Paulo, Vila Olímpia - SP] Desenvolvedor Java Pleno 

### ISSUE THREAD

**Issue by sergiobr** [soujava/vagas-java#32]
Vaga: Desenvolvedor Java Pleno
Vee Digital @ Vila Olímpia - SP

A Vee é uma Fintech na área de benefícios. Nascemos para fazer sempre o melhor negócio para nossos clientes. Uma empresa de benefícios, sem burocracias, segura, ágil e ética. Buscamos quebrar o atrito entre a cadeia de pagamentos para que nossos clientes sempre saiam ganhando.

Concebida por um grupo de executivos com as mais diferentes skills, das mais variadas áreas, a Vee chegou ao mercado em 2017, depois de dois anos de desenvolvimento e estudos de viabilidade. Tudo isso para garantir a melhor experiência para nossos clientes.

☛ Requisitos
⟹ Desejável ensino superior completo na área de computação ou tecnologia;
⟹ Experiência de ao menos 4 anos com desenvolvimento Java EE;
⟹ Sólidos conhecimentos em Java EE, Hibernate, JSF, MVC, padrões de projeto, boas práticas; 
⟹ Experiência com Maven, Wildfly, Webservices REST, PL/SQL, GIT, Amazon AWS;
⟹ Inglês avançado.
⟹ Diferenciais: conhecer PicketLink, Spring Boot;

☛ Atribuições
⟹ Desenvolver novas funcionalidades e analisar as atuais;
⟹ Entender problemas técnicos ou de negócio e criar soluções por meio de programação Java;
⟹ Criar testes de código automatizados para validação dos sistemas;
⟹ Participar ativamente durante as fases concepção do produto, análise de requisitos e propor alternativas mais eficientes;
⟹ Trabalhar sempre com a melhoria contínua dos sistemas e buscar formas de otimizar, refatorar e implementar novas tecnologias que atendam as necessidades de negócio da empresa.

☛ Oferecemos
⟹ Contratação CLT com benefícios;
⟹ Horário flexível;
⟹ Ambiente descontraído;
⟹ Uma grande oportunidade de aprendizagem e crescimento profissional, em conjunto com a expansão da empresa;
⟹ Fazer parte de um time inovador de desenvolvedores, ajudando a criar uma nova forma de realizar transações em programas de benefício corporativo que utiliza moeda digital e conceitos inspirados no Bitcoin e Blockchain.

☛ Como se candidatar
⟹ Preencha o formulário em https://goo.gl/forms/0cugHSBmxTBOjmHM2
⟹ Envie seu currículo para contato@vee.digital com o assunto “Vaga Desenvolvedor Java Pleno”

☛ Vee Digital Online
https://vee.digital/
https://www.instagram.com/vee.digital/
https://www.youtube.com/channel/UCDGuWimOqDsvohupvAcXOUA/featured

☛ Onde ficamos
Vila Olímpia
Rua Funchal, 538 - 16º andar – sala 165
São Paulo

**Comment by CesarNog** [comment]
@sergiobr, obrigado por postar esta vaga aqui!
