### ISSUE TITLE
[São Paulo, Vila Olímpia - SP] Desenvolvedor Pleno/Sênior

### ISSUE THREAD

**Issue by sergiobr** [soujava/vagas-java#33]
A Vee Digital está em busca de talentos.
Temos vagas em nosso escritório na Vila Olímpia - SP na área de
- Analista Desenvolvedor Pleno/Sênior

Buscamos pessoas interessada em fazer parte de um time de desenvolvedores que está trabalhando em uma nova forma de realizar transações em programas de benefício corporativo (Vales Refeição, Alimentação…), utilizando moeda digital, Bitcoin e Blockchain.

Envie seu currículo e enviaremos informações sobre os próximos passos do processo seletivo.

☛ Habilidades e conhecimentos exigidos:
⟹ Lógica de programação, algoritmos
⟹ Programação orientada a objetos, padrões e boas práticas
⟹ Controle de versão
⟹ Banco de Dados Relacionais (SQL)
⟹ Inglês para Leitura

☛  Experiência desejável :
⟹ Desenvolvimento Java EE

☛  Diferenciais:
⟹ TDD/BDD, testes automatizados, processos de Integração e Deploy contínuo
⟹ Metodologias Ágeis (Scrum, Kanban, XP, Lean)

☛ Como se candidatar
⟹ Preencha o formulário em https://goo.gl/forms/0cugHSBmxTBOjmHM2
⟹ Envie seu currículo para contato@vee.digital com o assunto “Vaga Desenvolvedor Java Pleno”

**Comment by CesarNog** [comment]
@sergiobr, obrigado por postar esta vaga aqui!
