### ISSUE TITLE
[Curitiba, Paraná] Dev. Java Batch | AutomTech [VAGA ENCERRADA]

### ISSUE THREAD

**Issue by AutomTech** [soujava/vagas-java#371]
**### Atividade:**
Fazer integração com usuário final, levantamento de requisitos e desenvolvimento de novas soluções.

**### Requisitos:**
- Java 8
- Spring Batch e Spring Integration
- Banco de dados Oracle

**Contratação CLT. Prazo Indeterminado.
![Java Batch](https://user-images.githubusercontent.com/57018306/68683378-70b4c980-0545-11ea-92f4-c505c59fdac8.png)
**

**Comment by jrxxjr** [comment]
Por favor, vocês tem vagas remotas ?


Evaldo Junior


Em Ter, 12 de nov de 2019 12:10, AutomTech - Soluções em TI <
notifications@github.com> escreveu:

**Comment by AutomTech** [comment]
Olá @jrxxjr,

No momento apenas presencial

**Comment by AutomTech** [comment]
Vaga preenchida! Agradecemos a todos que enviaram CVs.
