### ISSUE TITLE
[Curitiba, PR] DevOps | Improving

### ISSUE THREAD

**Issue by adriana-matos** [soujava/vagas-java#40]
Trabalha como DevOps, entende de AWS e quer trabalhar numa fintech que já é usada por dezenas de milhões de usuários da América Latina em uma cidade conhecida pela qualidade de vida como Curitiba?

Você será contratado em regime CLT full e irá trabalhar na sede da empresa no centro de Curitiba, cidade conhecida por ter as principais vantagens de se morar em uma capital combinadas com um excelente sistema de transporte, organização e custo de vida reduzido. Essa fintech com 5 anos de  existência oferece serviços financeiros consumidos por milhões de usuários na América Latina e já está presente em 6 países, com expansão já prevista para mais 4 em breve.

**Nessa oportunidade de trabalho você poderá:**

- Evoluir e expandir a automação da infraestrutura atual, que além de AWS (OpsWorks, RDS, EC2, Route53, VPC, S3, CloudFront, SES, ElastiCache, IAM etc.) já incorpora também serviços no Google Cloud, usando diferentes linguagens de programação, scripts e ferramentas de mercado;

- Ajudar a deixar o monitoramento (NewRelic, CloudWatch, Pingdom, OSSEC, PagerDuty etc) e segurança (PCI-DSS) ainda mais maduros, identificando pontos de falha e gerando planos de ação;

- Aprender muito todos os dias e superar novos desafios!

**Por que eu deveria me candidatar a essa vaga:**

- Ter a oportunidade de trabalhar numa fintech que está se expandindo mesmo na crise, que investirá no seu crescimento, num escritório que oferece opções de lazer e alimentação saudável e localizado numa capital com alta qualidade de vida;

- Trabalhar com um stack tecnológico de ponta, ajudando a definir a aplicação de novas tecnologias para evolução do negócio, boas práticas e gerando impacto direto no negócio e na vida de dezenas de milhões de pessoas;

- Você será contratado em regime CLT full, receberá aulas de inglês e espanhol no escritório, verba para investir em educação, Gympass, acesso ao SESC, plano de saúde e odontológico Bradesco Top Nacional e vale refeição, além de um plano de objetivos e carreira pra sua evolução profissional;

**Para se candidatar, você precisa ter:**

- Espírito de trabalho em equipe, comprometimento e vontade de pôr a mão na massa;

- Capacidade de aprender rapidamente tecnologias emergentes mediante ao consumo de livros, documentação técnica, vídeos ou palestras em inglês;

- Conhecimentos sólidos de Linux, redes, VPNs e firewalls;

- Domínio de tecnologias essenciais AWS via automação (comando de linha ou via linguagem de programação da sua preferência);

- Fluência em inglês para compreender ligações internacionais com clientes e fornecer informações básicas sobre como as requisições serão tratadas;

**Alguns diferenciais serão:**

- Experiência em Google Cloud Platform;

- Experiência em hardening, penetration testing e disciplinas correlatas de segurança, em especial atendendo o padrão PCI-DSS;

- Experiência em automação de infraestrutura (Puppet, Chef, Ansible, SaltStack, etc) e Docker;

- Experiência específica em administração e otimização de MySQL ou Postgres;

- Experiência com Apache ou nginx;

- Experiência com o uso de NewRelic, CloudWatch, Pingdom, OSSEC e PagerDuty para monitoramento;

Como se candidatar:

Basta entrar no seguinte link: https://goo.gl/xL1eEJ, preencher nome e email e te enviaremos as instruções.

**Comment by CesarNog** [comment]
@adriana-matos, obrigado por compartilhar esta vaga aqui conosco!
