### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Full-Stack Java / AngularJS / Android | Improving

### ISSUE THREAD

**Issue by adriana-matos** [soujava/vagas-java#63]
Gostaria de trabalhar como desenvolvedor full-stack com Java, AngularJS e Android com gestão ágil, num ramo com desafios algorítmicos interessantes, liberdade e autonomia?

Nessa empresa especializada em soluções logísticas com 15 anos de mercado, com escritório localizado na região do Itaim Bibi em São Paulo a cerca de 20 minutos a pé da estação Berrini, você desenvolverá e evoluirá aplicações web e aplicativos móveis nativos para otimização, planejamento e controle de rotas, em um negócio que foge dos meros sistemas de informação, com problemas algorítmicos interessantes e desafiadores.

Você atuará como desenvolvedor full-stack em regime CLT full, em um back-end baseado em Spring Boot, front-end com AngularJS e Bootstrap, uso de diversos bancos de dados (PostgreSQL, Oracle, SQL Server, etc.) e aplicativos mobile Android.

Quer você esteja iniciando na carreira ou já seja experiente, você poderá:

- Participar ativamente de todas as fases do desenvolvimento, num ambiente informal, com gestão baseada em Scrum, liberdade, que estimula o aprendizado - inclusive com a realização de hackatons internos -, e sem hierarquização;
- Trabalhar com tecnologias modernas de desenvolvimento como Spring Boot e Cloud, AngularJS, NodeJS, Android, entre outras;
- Aprender muito todos os dias e superar novos desafios!

**Por que eu deveria me candidatar a essa vaga:**

- Poder trabalhar num ramo de negócio diferenciado, que permitirá que você amplie seus conhecimentos de algoritmos e exerça sua criatividade na busca de soluções inovadoras;
- Ter liberdade e autonomia, podendo aprender e crescer, participando em todas as fases do desenvolvimento dos produtos e interagindo com todos, inclusive com a diretoria da empresa;
- Você será contratado em regime CLT, com salário entre R$ 5.500 e R$ 12.500 (dependendo de como você for avaliado), vale refeição, vale transporte, plano de saúde e odontológico (com desconto somente para dependentes), seguro de vida e PLR;

**Para se candidatar, você precisa ter:**

- Espírito de trabalho em equipe, comprometimento e vontade de pôr a mão na massa;
- Capacidade de aprender rapidamente tecnologias emergentes mediante ao consumo de livros, documentação técnica, vídeos ou palestras em inglês;
- Domínio de orientação a objetos, Java SE 8 (incluindo lambda) e suas APIs principais (java.lang, Collections, streams, etc);
- Domínio de arquiteturas RESTful e APIs com a plataforma Spring;
- Conhecimentos de desenvolvimento front-end moderno;
- Sólidos conhecimentos em bancos de dados relacionais

**Alguns diferenciais serão:**

- Vivência com Spring Boot e Cloud;
- Conhecimento específico de Postgres, SQL Server e/ou Oracle, incluindo procedures e otimizações de performance;
- Vivência com AngularJS, Bootstrap e NodeJS;
- Conhecimento em desenvolvimento de aplicações Android;
- Conhecimento prático de técnicas para escalar serviços e resolver problemas de performance;
- Conhecimentos de segurança;
- Conhecimentos de cloud, entrega contínua e automação de infraestrutura em geral

**Como se candidatar:**

Basta entrar no seguinte link: [https://goo.gl/eRxXNJ](https://goo.gl/eRxXNJ), preencher nome e email e te enviaremos as instruções.

**Comment by CesarNog** [comment]
Obrigado por compartilhar esta vaga conosco @adriana-matos ! =)
