### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Java Sênior - Vetta

### ISSUE THREAD

**Issue by nardnet** [soujava/vagas-java#68]
Nova oportunidade em aberto para Desenvolvedor Java Sênior.
Abaixo seguem algumas informações importantes:
 
·         Vaga para atuação em um dos nossos clientes, localizado em Belo Horizonte/MG
·         Valor CLT Full + benefícios ( ticket refeição, participação nos lucros, incentivo à capacitação, entre outros)
·         Tempo de alocação estimado: duração até dezembro/2018
  
Caso tenha indicação, solicitar o profissional para informar  pretensão salarial, enviar currículo atualizado e fazer o perfil em anexo.
 
Enviar para rh@vetta.com.br

**Comment by CesarNog** [comment]
Obrigado por compartilhar esta vaga conosco @nardnet !
