### ISSUE TITLE
[Curitiba - PR] Desenvolvedor Java Pleno & Sênior

### ISSUE THREAD

**Issue by andremoriya** [soujava/vagas-java#70]
A Meta Consultoria de TI está com vagas para Desenvolvedor Java Pleno e Sênior. 
Local: 1 vaga para Curitiba - PR 
Interessados enviar CV com pretensão salarial CLT, para cassiane.freitas@meta.com.br.

**Comment by CesarNog** [comment]
Obrigado por compartilhar esta vaga conosco @andremoriya  !
