### ISSUE TITLE
[Jaraguá do Sul - SC] Desenvolvedor Java Sênior 

### ISSUE THREAD

**Issue by andremoriya** [soujava/vagas-java#71]
Descrição das Atividades
•	Profissional irá atuar como Analista/Desenvolvedor JAVA; 
•	Realização de desenvolvimentos e testes unitários cumprindo prazos acordados. - Atendimento de chamados de níveis 2 e 3, atuando na análise de incidentes e problemas do Sistema com interação com áreas de negócio e TI bem como na documentação dos processos realizados baseados em ITIL e Cobit. 
•	Atendimentos a suportes (extrações de dados, intervenções na base de dados e demais atendimentos eventuais) e melhorias no sistema. 
•	Deverá ter experiência em projetos complexos e conhecimento em modelagem e desenvolvimento de sistemas em JAVA, elaboração de Layouts, front-end de aplicações, Web Services e Design Web. 

Conhecimentos Técnicos:
•	Ensino superior completo ou cursando em pós graduação em Tecnologia da Informação; 
•	Tenha atuado com projetos em tecnologia JAVA utilizando: RAD versão 8 ou superior, Eclipse, Hibernate, Tomcat, HTML, JavaScript, jQuery, CSS, Spring Framework; 
•	Experiência de no mínimo 5 anos em desenvolvimento JAVA; 
•	Conhecimento em Engenharia de Software; - Conhecimento em UML; - Conhecimento em ITIL; - Conhecimento em desenvolvimento de sistemas com métodos ágeis SCRUM; 
•	Experiência em elaboração de especificações técnicas. 
•	Testes unitários e integrados. 
•	Inglês intermediário; domínio da língua portuguesa com excelência na escrita.

Interessados enviar CV com pretensão salarial CLT, para cassiane.freitas@meta.com.br.

**Comment by CesarNog** [comment]
Obrigado por compartilhar a vaga aqui @andremoriya !

**Comment by andremoriya** [comment]
Atualizadas informações, vaga agora é para Sênior.

Obrigado

**Comment by andremoriya** [comment]
Irei fechar e abrir outra....
Peço desculpas
