### ISSUE TITLE
Desenvolvedor Java - Multinacional 

### ISSUE THREAD

**Issue by 1992yanara** [soujava/vagas-java#881]
JAVA
- Projetar e implementar novos recursos e componentes com base nos requisitos de negócios
- Conduzir revisões de código, documentação de design e implementação de metodologias Ágeis, para garantir software de alta qualidade
- Desenvolver aplicativos usando Java Spring
- Investigar e avaliar tecnologias novas e emergentes
- Solucionar e corrigir problemas de aplicativos de software
- Participar dos esforços de qualidade do processo de software

Skills
2+ anos de experiência em desenvolvimento Java
 Experiência em projetar, desenvolver e depurar serviços Restful Web e micro-serviços
 Java (Spring e SpringBoot) 
 Git, Maven

**Comment by KlausEverWalkingDev** [comment]
Acho que faltou falar a média salarial e os benefícios (se há algum). E suponho que seja uma oportunidade remota, correto?

**Comment by 1992yanara** [comment]
Olá Klaus,

Estamos oferecendo um target médio de até 12k PJ + benefícios.

Aqui em SP, mas podemos seguir com sistema flex working.

Abraços,

YANARA MEDEIROS
+ 55 11 5188 1600 | + 55 11 9 6649-3896
+ 55 21 2018 0238 | + 55 41 3180 0366
AV ENG. LUÍS CARLOS BERRINI, 1.748
15° ANDAR | SP | 04571 000
SÃO PAULO | RIO DE JANEIRO | CURITIBA
WWW.REDCONSULTING.COM.BR<http://www.redconsulting.com.br/>
CONECTE-SE A NÓS:
[Descrição: Descrição: Descrição: Descrição: linkedin-icon]<http://www.linkedin.com/company/red-recruiting-executives-&-development/>| [Descrição: Descrição: Descrição: Descrição: facebook_icon] <https://www.facebook.com/redrecruitingdevelopment>  | [Descrição: Descrição: Descrição: Descrição: TwitterIcon] <http://twitter.com/RedConsultingBr>

[Descrição: Descrição: LOGO RED ASSINATURA]


De: Klaus Ferreira ***@***.***>
Enviada em: segunda-feira, 17 de maio de 2021 17:18
Para: soujava/vagas-java ***@***.***>
Cc: Yanara Medeiros | RED CONSULTING ***@***.***>; Author ***@***.***>
Assunto: Re: [soujava/vagas-java] Desenvolvedor Java - Multinacional (#881)


Acho que faltou falar a média salarial e os benefícios (se há algum). E suponho que seja uma oportunidade remota, correto?
